# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default='TheGreatOne', max_length=255),
            preserve_default=False,
        ),
    ]
